[package]
name = "apm"
version = "0.1.0"
authors = ["Leo Shen <i@szclsya.me>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
regex = "1"
lazy_static = "1"
# Good stuff
varisat = "0.2"
# cli
console = "0.14.1"
