[package]
name = "apm"
version = "0.1.0"
authors = ["Leo Shen <i@szclsya.me>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
regex = "1"
lazy_static = "1"
# Solver
varisat = "0.2"
petgraph = "0.5"
rayon = "1"
# Dealing with deb control files
debcontrol = "0.1"
# cli
console = "0.14.1"
indicatif = "0.16"
dialoguer = "0.8"
# Dealing with config files
serde = "1"
toml = "0.5"
# Network stack
futures = "0.3"
tokio = { version = "1.8", default_features = false, features = ["rt", "macros", "fs", "io-util"] }
bytes = "1"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
